### PR TITLE
Fixed uniprot fetch, more tests and improved gencode assembly accession selector

### PR DESCRIPTION
**Pull request by Roleren**

### CODE REVIEW

**Comment by HajkD** [comment]
Hi @Roleren 

I think we just committed new features for the UniProt retrieval at the same time :)

Would it be possible to merge my newest commits and integrate with your changes?

Let me know if all went smoothly and I will then merge back to the main branch.

Many thanks,
Hajk

**Comment by Roleren** [comment]
It is already merged in, so no problem there.

I just see the getCDSSet still has an error related to what you sent in the email earlier. 

Will commit a fix for that before you merge this, will let you know when it is ready.

**Comment by Roleren** [comment]
Ok, I see the whole set of getXSet (getGFFSet etc) functions is very error prone and not generalized, when they all basically all do the same procedure. 

I need to do a small fix before we close this, will not generalize all of them, but make them a bit more safe at least.

Will be done by tomorrow morning.

**Comment by HajkD** [comment]
Sounds perfect! Many thanks for looking into this. Classic example of coding dept in academic software engineering :(

**Comment by Roleren** [comment]
Phew, that was a lot, all set operations are now generalized (see function getBioSet and getBio), it also has a safe checker for which species already exist in your set (using a stored csv instead of just checking the folder, which simply does not work most of the time).

It is also now very easy to extend what docs are being saved with collections etc, we can discuss this later.

Running final tests so wait for me to finish those before you merge.

**Comment by HajkD** [comment]
Wow, this is incredible work, @Roleren!!!! Thank you so much!

I will wait with the merge for your Go and we can then also change the vignettes to highlight these new `getBioSet()` features :)

**Comment by Roleren** [comment]
Will Improve some more docs before we merge, just a sec

**Comment by Roleren** [comment]
Ok, done, documentation is now generalized (for the most part), such that improving it will now be much simpler through inheritance.  

You can now merge this PR.

**Comment by HajkD** [comment]
Absolutely brilliant!!! Thank you so so much!


I can confirm that this works beautifully now:

```r
getCDSSet(db = "genbank", organisms = c("Homo sapiens", 
                                        "Mus musculus", 
                                        "Caenorhabditis elegans"), path = file.path(tempdir(), "CDS_set"))
```

I will now prepare the release and then we can discuss the resubmission to CRAN and the next steps.

With very best wishes,
Hajk

**Pull request merged**
