### PR TITLE
Fixed download of earlier release ensembl genomes

### PR DESCRIPTION
**Pull request by Roleren**

### CODE REVIEW

**Comment by Roleren** [comment]
Ok, good to go. 

Now protein, DNA fasta and DNA gtf all can access ensembl releases correctly down to 46

**Review by HajkD — COMMENTED** [review]
Hi Håkon,

Thank you so much for this fantastic work! 

This looks already very good!

I was wondering whether it would be possible to remove the `.gitignore` and `biomartr.Rproj` files?

Also did you intend to have the files https://github.com/ropensci/biomartr/pull/61/commits/4e804be45e426bed58029c55188b42632c663a11#diff-37a250f18367de0bfad6a62d1185f5cefe40b040d87a931ff91e7dd8e31b1095, https://github.com/ropensci/biomartr/pull/61/commits/4e804be45e426bed58029c55188b42632c663a11#diff-bb1fc76f2b917b76d717878d885089f85425717f3ffcb1342ef9c2dda26c6263,  https://github.com/ropensci/biomartr/pull/61/commits/4e804be45e426bed58029c55188b42632c663a11#diff-bb1fc76f2b917b76d717878d885089f85425717f3ffcb1342ef9c2dda26c6263, https://github.com/ropensci/biomartr/pull/61/commits/4e804be45e426bed58029c55188b42632c663a11#diff-e58c80fb18d02cb222525db2270dd7e31cc04fbccd200eb223a7f7b2facb27b5,  and https://github.com/ropensci/biomartr/pull/61/commits/4e804be45e426bed58029c55188b42632c663a11#diff-229c833c7c0b3966466ee67fb9fa4f235f3028473f9449c1da79dced1f0f91b4 within the package? Maybe we should remove them?

After addressing these small things, I am happy to merge!

Very well done!

Many thanks,
Hajk

**Comment by Roleren** [comment]
Yes, that was not intentional, looks like the tests create a subfolder. I removed .gitignore and biomartr too.

**Comment by HajkD** [comment]
Absolutely brilliant! Looks perfect now!

**Pull request merged**
