### PR TITLE
Massive update of generalized code and improvements

### PR DESCRIPTION
**Pull request by Roleren**
This is a very large commit, with thousands of lines changed, preliminary tests worked, I added some new ones too.

Wait to accept this until I run the final tests, some key points are:

1. Annotation did mean gff, but it should be both gff and gtf getter, with format specification, this is now fixed and generalized.
2. Generalize more urls (it is still very unsafe, and bloated)
3. Fix fungi collection
4. Add in protists support
5. update wrong paths
6. remove EnsemblGenome (it is an artificial split, which user can not know which to use)
7. Generalized code in general (e.g. getGTF is now just a wrapper to getGFF etc, with specified format)

### CODE REVIEW

**Comment by HajkD** [comment]
Incredible, @Roleren! Very very well done and thank you so so much!

I will wait with the merge until your go and will have a closer look as well.

With many thanks and very best wishes,
Hajk

**Comment by HajkD** [comment]
This is absolutely amazing, @Roleren!

Thank you so so much for all your efforts.

Would you also like to copy/paste and adjust a few of your key points in the NEWS.md file?
Once you are happy with having added all novelty there (and referenced to this PR), I will gladly merge right away.

With many thanks and very best wishes,
Hajk

**Comment by Roleren** [comment]
Okay, done, please check the news file that looks right, I tried to follow your old formatting style. 

I think it is ready to go, biomaRt is now bumped to version 1.05

**Comment by HajkD** [comment]
Brilliant! Thank you so much! I will also have a quick look into fixing the `getProtein()` retrieval from UniProt and then we can push the new version to CRAN. In the meantime we could also start addressing the open issues.

With many thanks and very best wishes,
Hajk

**Pull request merged**
