### PR TITLE
Assembly type argument implementation

### PR DESCRIPTION
**Pull request by Roleren**
Added arguments to getGenome, getGenomeSet and getGTF, and check for valid input of the argument. Also news and vignette. 

Let me know if something is unclear.

### CODE REVIEW

**Comment by HajkD** [comment]
Hi Håkon,

This is absolutely brilliant! Thank you so much!

I checked everything and it looks very good!

Would it be possible to make two small adjustments?

1) I didn't publish biomartr v1.0.0 yet (current version on CRAN is 0.9.2), hence renaming it to v1.0.1 is still too early.
It would be great if you could rename it back to v1.0.0 and integrate your bullet point within the NEWS section under biomartr v1.0.0 (which will be the next release)

2) Since the new `assembly_type` argument in `getGenomes()` can only be used for `db = "ensembl"`, it would be very useful to integrate a stop-check into the `getGenomes()` function:

```r
if ((db != "ensembl") && (assembly_type &in& c("toplevel", "primary_assembly")))
  stop( "The assembly_type argument is only valid for db = 'ensembl'.", call. = FALSE)
```

Your help with this is very much appreciated!

Best wishes,
Hajk

**Comment by Roleren** [comment]
To not change the API of the package, the check has to be like this:

if ((db != "ensembl") && (assembly_type != "toplevel"))
            stop( "The assembly_type argument is not default value.",
            "Don't change this argument when not using db = 'ensembl'.", call. = FALSE)

Since toplevel was what it was before, so it need to be default value, it will give error if you try to change assembly_type when not using ensembl. Sounds good or what you think ?

**Comment by HajkD** [comment]
> To not change the API of the package, the check has to be like this:
> 
> if ((db != "ensembl") && (assembly_type != "toplevel"))
> stop( "The assembly_type argument is not default value.",
> "Don't change this argument when not using db = 'ensembl'.", call. = FALSE)
> 
> Since toplevel was what it was before, so it need to be default value, it will give error if you try to change assembly_type when not using ensembl. Sounds good or what you think ?

Sounds excellent! I completely agree!

**Comment by Roleren** [comment]
OK, then I think that was it, unless you have something in mind ?

BTW, why does the check fail, does the travis CI not handle to use the ftp port 21 ?

**Comment by HajkD** [comment]
Looks excellent! Thank you very very much!
Yea, I have no idea why Travis stopped working... I thought it was a dependency it couldn't find for whatever reason, but I didn't think of the port yet. Could this be the case?

**Comment by Roleren** [comment]
This is error, it comes from running the example for listNCBIDatabases:
```

> # retrieve all versions of the NCBI 'nr' database that can be downloaded
> listNCBIDatabases(db = "nr")
Error in function (type, msg, asError = TRUE)  : 
Failed to connect to ftp.ncbi.nlm.nih.gov port 21: Connection timed out
Calls: listNCBIDatabases ... strsplit -> <Anonymous> -> curlPerform -> <Anonymous> -> fun
```

**Comment by HajkD** [comment]
Thanks for checking this! I added a `\dontrun` to the example of `listNCBIDatabases` and now the travis run passed smoothly!

**Pull request merged**
